### ISSUE TITLE
Google Gemini support

### ISSUE THREAD

**Issue by samrat** [thmsmlr/instructor_ex#45]
Hello!

Is anyone working on adding Gemini support already?

- API documentation: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini
- Gemini 1.5 Pro seems to have support for function calling.
- There seems to be two different ways of calling the API?  https://github.com/jxnl/instructor/issues/441#issuecomment-1951435515

**Comment by M-Gonzalo** [comment]
Yes, please! With the latest model Gemini Advanced, it rivals and sometimes surpasses GPT-4 (at least to my subjective taste). It's become my go-to LLM for daily use, especially given it can access the internet, read PDFs, watch videos, etc. I would definitely pick it over GPT stuff (even though they're great, and a close second)

**Comment by frozencap** [comment]
This would be awesome with the wildly generous free tier

**Comment by samrat** [comment]
Closing this as Thomas added Gemini support in https://github.com/thmsmlr/instructor_ex/pull/74
